# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.248
loader_version_range=[1,)

jei_version=19.21.0.247
mod_id=hmag
mod_name=Hostile Mobs and Girls
mod_license=LGPL-3.0
mod_version=9.0.38
mod_group_id=com.github.mechalopa.modid
mod_authors=Mechalopa
mod_description=More Hostile Mobs and Girls!!!
