modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Mechalopa/Hostile-Mobs-and-Girls/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://github.com/Mechalopa/Hostile-Mobs-and-Girls/raw/1.21.1/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/hostile-mobs-and-girls"
#logoFile="logo.png"
credits="Mechalopa"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="hmag.mixin.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[modproperties.${mod_id}]
    catalogueItemIcon="hmag:evil_crystal"
